### ISSUE TITLE
Bug: getStreamFormat regression in v5.13.4 — TypeError breaks all providers

### ISSUE THREAD

**Issue by noizo** [MadAppGang/claudish#77]
## Description

Upgrading from claudish v5.13.1 to v5.13.4 causes a `TypeError` that breaks all LLM providers:

```
TypeError: this.getAdapter().getStreamFormat is not a function
```

## Reproduction

```bash
npm install -g claudish@5.13.4
claudish -c ll@llama-3.3-70b-versatile --dangerously-skip-permissions "hello"
# TypeError: this.getAdapter().getStreamFormat is not a function
```

Downgrading to 5.13.1 resolves the issue:
```bash
npm install -g claudish@5.13.1
# Works fine
```

## Root Cause

In `packages/cli/src/handlers/composed-handler.ts`, the stream format resolution changed between versions:

**v5.13.1 (working) — line 616:**
```typescript
switch (this.provider.streamFormat) {
  case "openai-sse":
```

**v5.13.4 (broken) — lines 623-627:**
```typescript
const streamFormat = this.provider.overrideStreamFormat?.() ?? this.getAdapter().getStreamFormat();
switch (streamFormat) {
```

The new code calls `this.getAdapter().getStreamFormat()`, but `BaseModelAdapter` and its subclasses (`LiteLLMAdapter`, `OpenRouterAdapter`, `GeminiAdapter`, etc.) do not define a `getStreamFormat` method. The `overrideStreamFormat` optional chaining returns `undefined` for all current providers, so it always falls through to the missing method.

## Suggested Fix

Fall back to the provider's `streamFormat` property (which exists and worked in v5.13.1):

```typescript
const streamFormat = this.provider.overrideStreamFormat?.() ?? this.provider.streamFormat;
```

Or add `getStreamFormat()` to `BaseModelAdapter` that returns the provider's stream format.

## Environment

- claudish: 5.13.4 (broken), 5.13.1 (working)
- Claude CLI: 2.1.78
- Node.js: 22.x (LTS Alpine)
- Affects: all LiteLLM-routed providers (Groq, Gemini, OpenRouter, etc.)

**Comment by erudenko** [comment]
This was fixed — `getStreamFormat()` now exists on `BaseModelAdapter` (returns `"openai-sse"` by default) and is properly overridden by GeminiAdapter, AnthropicPassthroughAdapter, etc. The 3-tier stream format resolution works correctly:

```
transport.overrideStreamFormat() ?? modelAdapter.getStreamFormat() ?? formatAdapter.getStreamFormat()
```

If you're still on 5.13.4, please upgrade to the latest version. Thanks for the detailed report @noizo!
